---
title: Pianetararo website
author: Pianetararo Associazione Culturale
email: ''
description: ''
baseurl: "/"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
